/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package task_1_1_1

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'task_1_1_1.greeting' plugin.
 */
class Task_1_1_1PluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("task_1_1_1.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
